### ISSUE TITLE
Q-clsvpkg: How many base classes?

### ISSUE THREAD

**Issue by augustjanse** [texfaq/texfaq.github.io#21]
[This page](https://texfaq.org/FAQ-clsvpkg) states:

> Base LaTeX offers five classes of document: book, report, article and letter.

I count four.

**Comment by davidcarlisle** [comment]
ah good counting!


Actually latex/base has 10 classes


article.cls
book.cls
letter.cls
ltnews.cls
ltxdoc.cls
ltxguide.cls
minimal.cls
proc.cls
report.cls
slides.cls

but some are single purpose ones just intended for documenting the base sources.

I suspect that historically the list here said "five" and included slides.cls but slides.cls isn't really recommended these days, people tend to use beamer etc.

I suspect we want to change the wording and describe the 4 "main classes" or some such so we don't mention the others but phrase it in a way that is true and not self inconsistent...

**Comment by davidcarlisle** [comment]
Thanks for the comment, fixed I hope:-)
