### ISSUE TITLE
texfaq in different languages?

### ISSUE THREAD

**Issue by dbitouze** [texfaq/texfaq.github.io#22]
French speaking TeX users suffer from very old TeX FAQs ([here](https://2001-faq-latex.fr/) and [here](http://faqfctt.fr.eu.org/3.00.alpha/faqfr-20041111-3.00.alpha.pdf)) in their mother tongue.

We, at GUTenberg (French TUG), consider providing a new and up to date one and, for, this, consider starting by translating this current English FAQ (and, later, to update the old French ones, some questions of which could be added in the English one). If I'm right, it is possible from the license point of view.

Okay, we could just create a new Git repository and start the translations in our own corner but maybe it would be better for this French FAQ to be a subrepository of the current English one. And maybe there could be several subrepositories, one per language for which there would volunteers?

**Comment by josephwright** [comment]
I don't think there is any issue in creating additional repositories here for translations; the only thing is the technical side with GitHub Pages (if you want to use that approach)

**Comment by davidcarlisle** [comment]
If you have a separate git repository under the texfaq github organisation then it can have essentially the same github pages setup as for the english one which you could serve from github.io or a custom URL  as you choose.

**Comment by josephwright** [comment]
Sure: @dbitouze suggest a repo name and we'll make one and add you. We could make a separate 'team' for this repo if you like.

**Comment by dbitouze** [comment]
@josephwright 
>I don't think there is any issue in creating additional repositories here for translations;

Nice!

> the only thing is the technical side with GitHub Pages (if you want to use that approach)

Hmmm, I have no idea what is it but I'll have a look at it.

**Comment by dbitouze** [comment]
@josephwright 

> Sure: @dbitouze suggest a repo name and we'll make one and add you.

`texfaq-fr`?

> We could make a separate 'team' for this repo if you like.

Could be safer to not interfere by accident with the English (or others) FAQ.

**Comment by davidcarlisle** [comment]
> Hmmm, I have no idea what is it but I'll have a look at it.

If you check in markdown pages at

https://github.com/texfaq/texfaq.github.io

they appear via github pages on the website as

https://texfaq.github.io

which is aliased to

https://texfaq.org


So if you were to have a repository say texfaq-fr under this organisation it could appear immediately as

https://texfaq.github.io/texfaq-fr

hmm which may impact on the English faq's google site search, 

we might want to check that first...

**Comment by davidcarlisle** [comment]
@josephwright   looking at https://github.com/isaacs/github/issues/547  (which is a bit long) but looks like we can't avoid texfaq-fr appearing as a subdirectory of texfaq.org if done this way.

**Comment by josephwright** [comment]
@davidcarlisle  If we renamed the main repo, would that be workable?

**Comment by davidcarlisle** [comment]
On Thu, 13 Feb 2020 at 17:19, Joseph Wright <notifications@github.com>
wrote:

> @davidcarlisle <https://github.com/davidcarlisle> If we renamed the main
> repo, would that be workable?
>

I think so as then I think you should be able to specify CNAME separately
for each repository, might experiment in a throw-away github setup
elsewhere,

**Comment by dbitouze** [comment]
Thanks a lot to both of you!

**Comment by josephwright** [comment]
We've been looking at the hosting side of things. Using GitHub Pages, its not really possible to have two sites from one account. So perhaps the easiest approach is to use a separate repo.

**Comment by dbitouze** [comment]
>We've been looking at the hosting side of things. Using GitHub Pages, its not really possible to have two sites from one account. So perhaps the easiest approach is to use a separate repo.

@josephwright Do you mean https://github.com/texfaq/texfaq-fr shouldn't be used?

**Comment by davidcarlisle** [comment]
@dbitouze   yes see the test at

https://texfaq.org/tf-test/

you can't really prevent the second web site appearing as a sub directory of the existing one, which will affect site search and other things

It would I think be simpler if you simply copied the entire github organisation setup to texfaq-fr at the top level  and then you can serve the site as texfaq-fr.github.io  or via a custom URL if you have one available.

**Comment by dbitouze** [comment]
>It would I think be simpler if you simply copied the entire github organisation setup to texfaq-fr at the top level

At the top level of what?

> and then you can serve the site as texfaq-fr.github.io or via a custom URL if you have one available.

OK.

**Comment by davidcarlisle** [comment]
> At the top level of what?
I mean copy the entire structure, so have a github organisation texfaq-fr with a texfaq-fr.github.io  repository in it, rather than have a repository under this texfaq organisation.

I'm not sure would you want to start from an empty setup or you could clone the entire existing repository to get a working website, then translate the pages one by one?

**Comment by dbitouze** [comment]
>I mean copy the entire structure, so have a github organisation texfaq-fr with a texfaq-fr.github.io repository in it, rather than have a repository under this texfaq organisation.

OK.

>I'm not sure would you want to start from an empty setup or you could clone the entire existing repository to get a working website, then translate the pages one by one?

I guess, we would choose the second option, but I have to ask the other GUTenberg people.

Thanks!

**Comment by dbitouze** [comment]
Okay, we will probably copy the entire GitHub organization of the English FAQ and start to translate. Hence, I guess https://github.com/texfaq/texfaq-fr should be removed in order to avoid confusions.
