### ISSUE TITLE
Q-inst-texlive, Q-inst-miktexstar and Q-syswin32

### ISSUE THREAD

**Issue by lvjr** [texfaq/texfaq.github.io#49]
In `Q-inst-texlive`, `tlmgr update` is mentoned but not `tlmgr install`. Maybe the following lines could be added:
````
To install a single package, use:
```
tlmgr install <package>
```
````

In `Q-inst-miktexstar`, `mpm --install` is mentioned but this option is deprecated:
```
Warning: --install: this option has been deprecated; it will be removed from a future version of MiKTeX
```
Maybe it could be replaced with
````
Open a command shell, and type:
```
miktex packages install <package>
```
````

And `Q-syswin32` is quite outdated:

> The latest release of MiKTeX — version 2.9 — requires Windows XP, or later (so it does not work on Windows 2000 or earlier).

In fact, MiKTeX has dropped support for 32bit Windows and has deprecated Windows 7/8 (at this time a warning is showed when running latest MiKTeX console on Windows 7)

> but there is a CygWin build of TeX Live so you can have a current TeX system. 

It seems TeX Live 2023 will drop support for 32bit Windows and CygWin.

PS: maybe `Q-syswin32` can be renamed as `Q-syswindows`.

**Comment by davidcarlisle** [comment]
yes thanks, rather a lot of the faq is "showing it's age" some newer table packages get no mention for example:-)  But I'll try to update this page.

**Comment by davidcarlisle** [comment]
@lvjr  thanks, I hope  have addressed all your comments.
