### ISSUE TITLE
Mention new packages in https://texfaq.org/FAQ-underline and comparisons

### ISSUE THREAD

**Issue by user202729** [texfaq/texfaq.github.io#52]
Consider mentioning `soulpos` and `lua-ul` too.

It would also be good to have a comparison between them e.g.

* the depth of the underline is consistent unlike `\underline` (https://tex.stackexchange.com/questions/13377/how-can-i-underline-a-single-word-with-latex#comment583953_13382)
* `lua-ul` can handle arbitrary commands inside the argument
* `soul` doesn't support Unicode character such as Ü (https://tex.stackexchange.com/a/142359/250119)
* `soulpos` supports nonhomogeneous decoration (e.g. wavy line), but requires two compilation passes
* `ulem` doesn't support hyphenation (https://tex.stackexchange.com/a/74910/250119)

**Comment by davidcarlisle** [comment]
I added some basic references to both these packages, thanks.
