### ISSUE TITLE
a typo in Q-fontsize

### ISSUE THREAD

**Issue by lvjr** [texfaq/texfaq.github.io#53]
I think `type1xx` should be `type1cm` in Q-fontsize:
```md
... doesn't do the job, try the [`type1xx`](https://ctan.org/pkg/type1cm)
packages ...
```

**Comment by davidcarlisle** [comment]
actually it looks like `type1`_xx_  was intended to mean both `type1cm` and `type1ec` but the "meta" formatting of the xx has been lost in the conversion to markdown. Also the whole reason for mentioning those packages seems to be that `fix-cm` is "new" and not in releases before 2003 which doesn't really make sense any more.

I'll adjust, thanks,

**Comment by davidcarlisle** [comment]
Wording adjusted, I hope it's clearer now, thanks.
